services:
  # Common configuration for all of our core uservices
  oada-uservice:
    build:
      context: ./oada
      target: ${TARGET-}
    restart: unless-stopped
    networks:
      startup_net: {}
      kafka_net: {}
      arango_net: {}
    volumes:
      - ./oada/oada.config.mjs:/oada.config.mjs # for debug?
    environment:
      # Default to loading packaged default config?
      CONFIG: ${OADA_CONFIG-/oada.config.mjs}
      # Default to development
      NODE_ENV: ${NODE_ENV-development}
      NODE_OPTIONS: $$INSPECT --enable-source-maps --unhandled-rejections=strict
      INSPECT: ${INSPECT---inspect=0.0.0.0:9229}
      DEBUG: ${DEBUG-*}
      PINO_LEVEL: ${PINO_LEVEL-debug}
      PINO_LOKI: ~
      PINO_LOKI_LEVEL: ~
      PROM_HOST: '::'
      DEBUG_HIDE_DATE: ~
      DEBUG_COLORS: ~
      DEBUG_DEPTH: ~
      DEBUG_SHOW_HIDDEN: ~
      # Should just be an external script someone can run on their instance?
      arangodb__ensureDefaults: 'true'
      DOMAIN: ${DOMAIN:-localhost}
      OIDC_ISSUER: ~
      NODE_TLS_REJECT_UNAUTHORIZED: ~
      PINO_TRANSPORT: ~
      PROFILE_AQL: ~
      # Allow changing arangodb URL (e.g., to use external arango)
      ARANGODB_URL: ${ARANGODB_URL-http://arangodb:8529}
      # Allow changing kafka brokers (e.g., to use external kafka)
      KAFKA_BROKERS: ${KAFKA_BROKERS-kafka:9092}
