{{/* vim: set ft=helm : */}}
{{/*
   * Copyright 2022 Open Ag Data Alliance
   *
   * Licensed under the Apache License, Version 2.0 (the "License");
   * you may not use this file except in compliance with the License.
   * You may obtain a copy of the License at
   *
   *     http://www.apache.org/licenses/LICENSE-2.0
   *
   * Unless required by applicable law or agreed to in writing, software
   * distributed under the License is distributed on an "AS IS" BASIS,
   * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   * See the License for the specific language governing permissions and
   * limitations under the License.
   */}}
{{- if eq (include "oada.arango.deploy" .) "true" }}
apiVersion: database.arangodb.com/v1
kind: ArangoDeployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: arangodb-{{ .Release.Name }}
  labels:
    app.kubernetes.io/component: arangodb
    {{- include "oada.chart.labels" . | nindent 4 }}
spec:
  image: {{ .Values.arangodb.image }}:{{ .Values.arangodb.tag }}
  mode: Single
  single:
    volumeClaimTemplate:
      metadata:
        annotations:
          helm.sh/resource-policy: keep
    resources:
      {{- toYaml .Values.oada.resources | nindent 6 }}
  environment: {{ .Values.global.development | ternary "Development" "Production" }}
  metrics:
    enabled: {{ include "oada.prometheus" . }}
  externalAccess:
    {{- /* Disable external access for Production */}}
    type: {{ .Values.global.development | ternary "Auto" "None" }}
  tls:
    caSecretName: None
  {{- if not .Values.global.development }}
  {{- /* Create root password for Production */}}
  bootstrap:
    passwordSecretNames:
      root: {{ include "oada.arango.rootPassword" . }}
  {{- end }}
{{- end }}