{{- if eq (include "oada.arango.deploy" .) "true" }}
apiVersion: database.arangodb.com/v1
kind: ArangoDeployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: arangodb-{{ .Release.Name }}
  labels:
    app.kubernetes.io/name: arangodb
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- include "oada.chart.labels" . | nindent 4 }}
spec:
  image: {{ .Values.arangodb.image }}:{{ .Values.arangodb.tag }}
  mode: Single
  environment: {{ .Values.global.development | ternary "Development" "Production" }}
  externalAccess:
    {{/* Disable external access for Production */}}
    type: {{ .Values.global.development | ternary "Auto" "None" }}
  tls:
    caSecretName: None
  {{- if not .Values.global.development }}
  {{/* Create root password for Production */}}
  bootstrap:
    passwordSecretNames:
      root: {{ include "oada.arango.rootPassword" . }}
  {{- end }}
{{- end }}