{{/*
   * Copyright 2022 Open Ag Data Alliance
   *
   * Licensed under the Apache License, Version 2.0 (the "License");
   * you may not use this file except in compliance with the License.
   * You may obtain a copy of the License at
   *
   *     http://www.apache.org/licenses/LICENSE-2.0
   *
   * Unless required by applicable law or agreed to in writing, software
   * distributed under the License is distributed on an "AS IS" BASIS,
   * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   * See the License for the specific language governing permissions and
   * limitations under the License.
   */}}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Chart.Name }}-configmap-{{ .Release.Name }}
  labels:
    app.kubernetes.io/component: {{ .Chart.Name }}-configmap
    {{- include "oada.chart.labels" . | nindent 4 }}
{{- if not .Values.global.development }}
#immutable: true
{{- end }}
data:
  #CONFIG: /oada.config.mjs
  DEBUG: {{ .Values.debug | join "," | quote }}
  PINO_LEVEL: {{ .Values.pino.level }}
  PINO_LOKI: {{ .Values.pino.loki.url | quote }}
  PROM_HOST: '::'
  DOMAIN: {{ include "oada.domain" . }}
  # Have OADA http handle rate-limit until we can get k8s to do it
  RATE_LIMIT_ENABLED: {{ .Values.oada.rateLimit.enabled | quote }}
  RATE_LIMIT_DRAFT_SPEC: {{ .Values.oada.rateLimit.useDraftSpec | quote }}
  MAX_READ_REQUESTS: {{ .Values.oada.rateLimit.max.reads | quote }}
  MAX_WRITE_REQUESTS: {{ .Values.oada.rateLimit.max.writes | quote }}
  RATE_TIME_WINDOW: {{ .Values.oada.rateLimit.timeWindow | quote }}
  NODE_OPTIONS: "$$INSPECT --enable-source-maps --unhandled-rejections=strict"
  {{ if eq (include "oada.arango.deploy" .) "true" -}}
  ARANGODB_URL: {{ include "oada.arango.connection" . }}
  {{- end }}
  ARANGODB_DATABASE: {{ .Values.arangodb.database }}
  PROFILE_AQL: {{ .Values.arangodb.profileAql | default (ternary 1 0 .Values.global.development) | quote }}
  {{ if eq (include "oada.kafka.deploy" .) "true" -}}
  KAFKA_BROKERS: {{ include "oada.kafka.brokers" . }}
  {{- end }}
  {{ if .Values.oauth.issuer -}}
  OIDC_ISSUER: {{ .Values.oauth.issuer | quote }}
  WELLKNOWN_SUBSERVICES: ''
  {{ else -}}
  # Use our internal Auth server
  OIDC_ISSUER: http://auth-{{ .Release.Name }}/oadaauth
  AUTH_PREFIX: /oadaauth/
  WELLKNOWN_SUBSERVICES: http://auth-{{ .Release.Name }}/oadaauth/
  {{- end }}
  {{ if .Values.global.development -}}
  NODE_ENV: development
  #NODE_TLS_REJECT_UNAUTHORIZED: '0'
  arangodb__ensureDefaults: 'true'
  INSPECT: '--inspect=0.0.0.0:9229'
  {{ else -}}
  NODE_ENV: production
  {{- end }}
