{{/*
   * Copyright 2022 Open Ag Data Alliance
   *
   * Licensed under the Apache License, Version 2.0 (the "License");
   * you may not use this file except in compliance with the License.
   * You may obtain a copy of the License at
   *
   *     http://www.apache.org/licenses/LICENSE-2.0
   *
   * Unless required by applicable law or agreed to in writing, software
   * distributed under the License is distributed on an "AS IS" BASIS,
   * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   * See the License for the specific language governing permissions and
   * limitations under the License.
   */}}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: http-handler-{{ .Release.Name }}
  labels:
    app.kubernetes.io/name: http-handler
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- include "oada.chart.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: http-handler
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.oada.ingress }}
---
# TODO: Why do I get an error with just `path: /`?
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: websocket-ingress-{{ .Release.Name }}
  labels:
    app.kubernetes.io/name: websocket-ingress
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{ include "oada.chart.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/issuer: letsencrypt-{{ .Release.Name }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - '{{ .Values.oada.domain }}'
      secretName: tls-{{ .Release.Name }}
  rules:
    - host: '{{ .Values.oada.domain }}'
      http:
        paths:
          - pathType: Exact
            backend:
              service:
                name: http-handler-{{ .Release.Name }}
                port:
                  name: http
            path: /$
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: http-ingress-{{ .Release.Name }}
  labels:
    app.kubernetes.io/name: websocket-ingress
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{ include "oada.chart.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/issuer: letsencrypt-{{ .Release.Name }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - '{{ .Values.oada.domain }}'
      secretName: tls-{{ .Release.Name }}
  rules:
    - host: '{{ .Values.oada.domain }}'
      http:
        paths:
          - path: /resources
            pathType: Prefix
            backend:
              service:
                name: http-handler-{{ .Release.Name }}
                port:
                  name: http
          - path: /bookmarks
            pathType: Prefix
            backend:
              service:
                name: http-handler-{{ .Release.Name }}
                port:
                  name: http
          - path: /shares
            pathType: Prefix
            backend:
              service:
                name: http-handler-{{ .Release.Name }}
                port:
                  name: http
          - path: /users
            pathType: Prefix
            backend:
              service:
                name: http-handler-{{ .Release.Name }}
                port:
                  name: http
          - path: /authorizations
            pathType: Prefix
            backend:
              service:
                name: http-handler-{{ .Release.Name }}
                port:
                  name: http
{{- end }}
