{{/*
   * Copyright 2022 Open Ag Data Alliance
   *
   * Licensed under the Apache License, Version 2.0 (the "License");
   * you may not use this file except in compliance with the License.
   * You may obtain a copy of the License at
   *
   *     http://www.apache.org/licenses/LICENSE-2.0
   *
   * Unless required by applicable law or agreed to in writing, software
   * distributed under the License is distributed on an "AS IS" BASIS,
   * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   * See the License for the specific language governing permissions and
   * limitations under the License.
   */}}
{{- $initName := print "init-" .Release.Name -}}
{{- if empty (lookup "batch/v1" "Job" .Release.Namespace $initName) -}}
{{- $tag := default .Chart.AppVersion .Values.oada.tag -}}
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Release.Namespace }}
  name: init-{{ .Release.Name }}
  labels:
    app.kubernetes.io/component: init
    {{- include "oada.chart.labels" . | nindent 4 }}
spec:
  backoffLimit: 10
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: service-account-{{ .Release.Name }}
      initContainers:
        {{ if eq (include "oada.arango.deploy" .) "true" -}}
        - name: wait-for-arangodb
          image: {{ .Values.k8sWaitFor.image }}:{{ .Values.k8sWaitFor.tag }}
          args:
            - service
            - arangodb-{{ .Release.Name }}
          resources:
            limits: {{- toYaml $.Values.k8sWaitFor.resources.limits | nindent 14 }}
            requests: {{- toYaml $.Values.k8sWaitFor.resources.limits | nindent 14 }}
        {{- end }}
        {{ if eq (include "oada.kafka.deploy" .) "true" -}}
        - name: wait-for-redpanda
          image: {{ .Values.k8sWaitFor.image }}:{{ .Values.k8sWaitFor.tag }}
          args:
            - service
            - redpanda-{{ .Release.Name }}
          resources:
            limits: {{- toYaml $.Values.k8sWaitFor.resources.limits | nindent 14 }}
            requests: {{- toYaml $.Values.k8sWaitFor.resources.limits | nindent 14 }}
        {{- end }}
      containers:
        - name: init
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-configmap-{{ .Release.Name }}
          env:
            - name: ARANGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "oada.arango.rootPassword" . }}
                  key: username
                  optional: {{ .Values.global.development }}
            - name: ARANGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "oada.arango.rootPassword" . }}
                  key: password
                  optional: {{ .Values.global.development }}
            - name: EXIT
              value: 'true'
          {{ if $.Values.global.development -}}
          ports:
            - name: inspect
              containerPort: 9229
          {{- end }}
          image: oada/startup:{{ $tag }}
          #imagePullPolicy: {{ .Values.global.development | ternary "Always" "IfNotPresent" }}
          resources:
            limits: {{- toYaml $.Values.oada.resources.limits | nindent 14 }}
            requests: {{- toYaml $.Values.oada.resources.limits | nindent 14 }}
{{- end -}}