{{/*
   * Copyright 2022 Open Ag Data Alliance
   *
   * Licensed under the Apache License, Version 2.0 (the "License");
   * you may not use this file except in compliance with the License.
   * You may obtain a copy of the License at
   *
   *     http://www.apache.org/licenses/LICENSE-2.0
   *
   * Unless required by applicable law or agreed to in writing, software
   * distributed under the License is distributed on an "AS IS" BASIS,
   * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   * See the License for the specific language governing permissions and
   * limitations under the License.
   */}}
{{- $tag := default .Chart.AppVersion .Values.oada.tag -}}
{{- range .Values.oada.users -}}
{{- $secretName := print "user-" .name "-" $.Release.Name -}}
{{- if empty (lookup "v1" "Secret" $.Release.Namespace $secretName) -}}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ $.Release.Namespace }}
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/component: users
    {{- include "oada.chart.labels" $ | nindent 4 }}
stringData:
  {{/* Generate random token */}}
  {{- $token := uuidv4 -}}
  token: {{ $token }}
  header: >
    Authorization: Bearer {{ $token }}
{{- end }}
---
{{- $jobName := print "user-add-" .name "-" $.Release.Name -}}
{{- if empty (lookup "batch/v1" "Job" $.Release.Namespace $jobName) -}}
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ $.Release.Namespace }}
  name: {{ $jobName }}
  labels:
    app.kubernetes.io/component: init
    {{- include "oada.chart.labels" $ | nindent 4 }}
spec:
  backoffLimit: 10
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: service-account-{{ $.Release.Name }}
      initContainers:
        - name: wait-for-init
          image: {{ $.Values.k8sWaitFor.image }}:{{ $.Values.k8sWaitFor.tag }}
          args:
            - job
            - init-{{ $.Release.Name }}
          resources:
            limits: {{- toYaml $.Values.k8sWaitFor.resources.limits | nindent 14 }}
            requests: {{- toYaml $.Values.k8sWaitFor.resources.limits | nindent 14 }}
        - name: wait-for-users
          image: {{ $.Values.k8sWaitFor.image }}:{{ $.Values.k8sWaitFor.tag }}
          args:
            - pod
            - '-l app.kubernetes.io/component=users,app.kubernetes.io/instance={{ $.Release.Name }}'
          resources:
            limits: {{- toYaml $.Values.k8sWaitFor.resources.limits | nindent 14 }}
            requests: {{- toYaml $.Values.k8sWaitFor.resources.limits | nindent 14 }}
        - name: user-add
          envFrom:
            - configMapRef:
                name: {{ $.Chart.Name }}-configmap-{{ $.Release.Name }}
          env:
            - name: ARANGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "oada.arango.rootPassword" $ }}
                  key: username
                  optional: {{ $.Values.global.development }}
            - name: ARANGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "oada.arango.rootPassword" $ }}
                  key: password
                  optional: {{ $.Values.global.development }}
          {{ if $.Values.global.development -}}
          ports:
            - name: inspect
              containerPort: 9229
          {{- end }}
          image: oada/users:{{ $tag }}
          #imagePullPolicy: {{ $.Values.global.development | ternary "Always" "IfNotPresent" }}
          command: ["/usr/bin/dumb-init", "--rewrite", "15:2", "--", "/bin/sh"]
          args: ["-c", "yarn workspace @oada/users run add -u {{ .name }} -a {{ .admin | default false }} "]
          resources:
            limits: {{- toYaml $.Values.oada.resources.limits | nindent 14 }}
            requests: {{- toYaml $.Values.oada.resources.limits | nindent 14 }}
      containers:
        - name: token-create
          envFrom:
            - configMapRef:
                name: {{ $.Chart.Name }}-configmap-{{ $.Release.Name }}
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: token
            - name: ARANGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "oada.arango.rootPassword" $ }}
                  key: username
                  optional: {{ $.Values.global.development }}
            - name: ARANGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "oada.arango.rootPassword" $ }}
                  key: password
                  optional: {{ $.Values.global.development }}
          {{ if $.Values.global.development -}}
          ports:
            - name: inspect
              containerPort: 9229
          {{- end }}
          image: oada/auth:{{ $tag }}
          imagePullPolicy: {{ $.Values.oada.imagePullPolicy }}
          command: ["/usr/bin/dumb-init", "--rewrite", "15:2", "--", "/bin/sh"]
          args: ["-c", "yarn workspace @oada/auth run token create -u {{ .name }} -s {{ .scope | join "," }} ${TOKEN} "]
          resources:
            limits: {{- toYaml $.Values.oada.resources.limits | nindent 14 }}
            requests: {{- toYaml $.Values.oada.resources.limits | nindent 14 }}
---
{{- end -}}
{{- end }}