{{/*
   * Copyright 2022 Open Ag Data Alliance
   *
   * Licensed under the Apache License, Version 2.0 (the "License");
   * you may not use this file except in compliance with the License.
   * You may obtain a copy of the License at
   *
   *     http://www.apache.org/licenses/LICENSE-2.0
   *
   * Unless required by applicable law or agreed to in writing, software
   * distributed under the License is distributed on an "AS IS" BASIS,
   * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   * See the License for the specific language governing permissions and
   * limitations under the License.
   */}}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: well-known-{{ .Release.Name }}
  labels:
    app.kubernetes.io/component: well-known
    {{- include "oada.chart.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/component: well-known
{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: well-known-ingress-{{ .Release.Name }}
  labels:
    app.kubernetes.io/component: well-known
    {{ include "oada.chart.labels" . | nindent 4 }}
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-{{ .Release.Name }}
spec:
  {{ if .Values.ingress.className -}}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  tls:
    - hosts: {{ default (list "localhost") .Values.oada.domains | toJson }}
      secretName: {{ include "oada.tls" . }}
  rules:
    {{ if empty .Values.oada.domains -}}
    - http:
        paths:
          - path: /.well-known/
            pathType: Prefix
            backend:
              service:
                name: well-known-{{ .Release.Name }}
                port:
                  name: http
    {{- end }}
    {{- range .Values.oada.domains -}}
    - host: {{ quote . }}
      http:
        paths:
          - path: /.well-known/
            pathType: Prefix
            backend:
              service:
                name: well-known-{{ $.Release.Name }}
                port:
                  name: http
    {{ end -}}
{{- end }}
