apiVersion: v2
name: oada
description: A Helm chart for the OADA API server
sources:
  - https://github.com/OADA/server
icon: https://avatars.githubusercontent.com/u/6750653
maintainers:
  - name: awlayton
    email: alex@layton.in
type: application
version: 3.3.2
appVersion: '3.9.1'
annotations:
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
    - url: https://artifacthub.io/packages/helm/redpanda/redpanda-operator
    - url: https://artifacthub.io/packages/helm/source-field/kube-arangodb
    - url: https://artifacthub.io/packages/helm/source-field/kube-arangodb-crd
    - url: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
