replicaCount: 1

oada:
  # oada.domain is the domain for this OADA instance
  domain: localhost
  # oada.ingress is whether to create ingresses into the OADA API
  ingress: true
  # oada.tag is the Docker tag for the OADA images
  tag: ~
  # oada.services is the list of oada services to deploy
  services:
    http-handler:
      http: true
    well-known:
      http: true
    auth:
      http: true
    shares: {}
    rev-graph-update: {}
    sync-handler: {}
    users: {}
    webhooks: {}
    write-handler: {}
  # oada.users is a list of users to be created
  users:
    - name: admin
      admin: true
      scope:
        - all:all
        - oada.admin.user:all
  resources: {}

# debug is the list of debug.js namespaces to enable/disable
debug:
  - '*'

pino:
  # pino.level is the level of messages to send to the pino transport
  level: info

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

arangodb:
  # arangodb.database is the ArangoDB database to use
  database: oada
  # arangodb.connection is a URI of an external ArangoDB server.
  # If this is set, the ArangoDB service will not be deployed.
  # If this is not set, the kube-arango operator will be used to deploy a cluster.
  connection: ''
  # arangodb.image is the Docker image to use for arangodb
  image: arangodb/arangodb
  # arangodb.tag is the Docker tag for the ArangoDB images
  tag: 3.9.2

kafka:
  # kafka.brokers is an array of an external Kafka brokers.
  # If this is not empty, the Redpanda service will not be deployed.
  # If this is empty, the redpanda operator will be used to deploy a cluster.
  brokers: []
  # kafka.image is the Docker image to use for Kafka
  image: vectorized/redpanda
  # kafka.tag is the Docker tag for the Kafka/Redpanda images
  tag: v22.1.3

k8sWaitFor:
  image: groundnuty/k8s-wait-for
  tag: v1.6

global:
  # global.development is whether to enable development/debug features not meant for production use
  development: false
