module.exports = [
  {
    '_id': 'users/default:users_frank_123',
    'username': 'frank',
    'password': 'test',
    'domain': 'localhost',
    'name': 'Farmer Frank',
    'family_name': 'Frank',
    'given_name': 'Farmer',
    'middle_name': '',
    'nickname': 'Frankie',
    'email': 'frank@openag.io',
    'bookmarks': {'_id': 'resources/default:resources_bookmarks_123'},
    'shares': {'_id': 'resources/default:resources_shares_123'},
  },
  {
    '_id': 'users/default:users_frank2_124',
    'domain': 'localhost',
    'username': 'dummy_username_oidcuser_frank2',
    'oidc': {
      'sub': 'users/default:users_gary_growersync', // can login as Frank at growersync.fpad.io
      'iss': 'api.growersync.fpad.io', // iss = issuer
    },
    'name': 'Gary Grower 2',
    'family_name': 'Gary2',
    'given_name': 'Grower2',
    'middle_name': '',
    'nickname': 'Gary2',
    'email': 'gary@openag.io',
    'bookmarks': {'_id': 'resources/default:resources_bookmarks_124'},
    'shares': {'_id': 'resources/default:resources_shares_124'},
  },
  {
    '_id': 'users/default:users_sam_321',
    'username': 'sam',
    'password': 'test',
    'domain': 'localhost',
    'name': 'Student Sam',
    'family_name': 'Student',
    'given_name': 'Sam',
    'middle_name': '',
    'nickname': 'Sammy',
    'email': 'sam@openag.io',
    'bookmarks': {'_id': 'resources/default:resources_bookmarks_321'},
    'shares': {'_id': 'resources/default:resources_shares_321'}
  },
  {
    '_id': 'users/default:users_audrey_999',
    'username': 'audrey',
    'password': 'test',
    'domain': 'abcaudits.fpad.io',
    'name': 'Auditor Audrey',
    'family_name': 'Auditor',
    'given_name': 'Audrey',
    'middle_name': '',
    'nickname': 'Audinator',
    'email': 'audrey@openag.io',
    'bookmarks': {'_id': 'resources/default:resources_bookmarks_999'},
    'shares': {'_id': 'resources/default:resources_shares_999'}
  },
  {
    '_id': 'users/default:users_gary_growersync',
    'username': 'gary@gmail.com',
    'password': 'test',
    'domain': 'growersync.fpad.io',
    'name': 'Grower Gary',
    'family_name': 'Grower',
    'given_name': 'Gary',
    'middle_name': '',
    'nickname': 'G-Man',
    'email': 'gary@gmail.com',
    'bookmarks': {'_id': 'resources/default:resources_bookmarks_777'},
    'shares': {'_id': 'resources/default:resources_shares_777'}
  },
];
