/**
 * @license
 * Copyright 2017-2021 Open Ag Data Alliance
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// eslint-disable-next-line no-secrets/no-secrets
export default 'eyJqa3UiOiJodHRwczovL2lkZW50aXR5Lm9hZGEtZGV2LmNvbS9jZXJ0cyIsImtpZCI6ImtqY1NjamMzMmR3SlhYTEpEczNyMTI0c2ExIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJyZWRpcmVjdF91cmlzIjpbImh0dHBzOi8vbG9jYWxob3N0L29hZGFhdXRoL2lkLXJlZGlyZWN0Il0sInRva2VuX2VuZHBvaW50X2F1dGhfbWV0aG9kIjoidXJuOmlldGY6cGFyYW1zOm9hdXRoOmNsaWVudC1hc3NlcnRpb24tdHlwZTpqd3QtYmVhcmVyIiwiZ3JhbnRfdHlwZXMiOlsiYXV0aG9yaXphdGlvbl9jb2RlIl0sInJlc3BvbnNlX3R5cGVzIjpbInRva2VuIiwiY29kZSIsImlkX3Rva2VuIiwiaWRfdG9rZW4gdG9rZW4iLCJjb2RlIGlkX3Rva2VuIiwiY29kZSB0b2tlbiIsImNvZGUgaWRfdG9rZW4gdG9rZW4iXSwiY2xpZW50X25hbWUiOiJMb2NhbGhvc3QiLCJjbGllbnRfdXJpIjoiaHR0cHM6Ly9sb2NhbGhvc3QiLCJjb250YWN0cyI6WyJBYXJvbiBBdWx0IDxhdWx0YWNAcHVyZHVlLmVkdT4iXSwiandrcyI6eyJrZXlzIjpbeyJraWQiOiI5MEQwMEE5OTdCNzc0QUQ0QjNCNEVFQjBFODREQzZDRiIsImt0eSI6IlJTQSIsIm4iOiI2QTJ3ZVY5eERhSWFyYWhTdkNTcFFqdC00b0I1ZVFYSWN0bWtnejdBODNQSjRWQ0IxNkRmbk9HMFUwV2FsdkdwVjJ4cEt6RkRmYzVQVFQ5UGNJX3BWaDBMQ0tWN2FvZmhtRHpqbWZad2lHWnpobzI1WHZ0d3ZBRFV0OTFCZnB3NmhKODY3Z1htRmJPcGFYRW5ZYk8yTUJvdzBtMmFLa1B5RTJpRm45aFFRbDZxM1h0YkFhZWppWVlLeGIxbkxRaHBjYkxYWDZ3ajVuUjYyTTd3eTVjTkJQVHRVbXBKaEtNbXlwNDMtM0JJNFg0ejB3ZXpVWEc5dmxhSGk5UEhDdG1DV2g2eUVNQk1abFlMaDJhd2ZJUW94NkpRaFIzTkVKMXRUVzlnRTdpMER3NnhsTjR2ZG1qM0VpWDZuS1VhWG9mM252QlNZVi0tV01YbWpwSDdxb09Ca1EiLCJlIjoiQVFBQiJ9XX0sInNvZnR3YXJlX2lkIjoiYTdlMjJkMTAtYzEzMS00OWM4LTkzOGItZmFhODExZjJiMjZjIiwicmVnaXN0cmF0aW9uX3Byb3ZpZGVyIjoiaHR0cHM6Ly9pZGVudGl0eS5vYWRhLWRldi5jb20iLCJpYXQiOjE1MDU3OTA4NDZ9.CoNNTADZ4tGufGT7f_hNSinu4HeT1nvA3eybHyZHV6MWeXw6wGvxw9hWTmvaFdlnDnhcDJ-gPCLtzs1dRZR5Vf-UF3vqZJVMOqoWIhRJnGYWmVleODwFzj2NcRjh-XiDWydPdOSWLvV7b1A6TG94_OUnzmfMnMEZ3PAeBQp66Tg';
