packageExtensions:
  "@fastify/accepts@*":
    peerDependencies:
      fastify: "*"
  "@fastify/bearer-auth@*":
    peerDependencies:
      fastify: "*"
  "@fastify/cors@*":
    peerDependencies:
      fastify: "*"
  "@fastify/formbody@*":
    peerDependencies:
      fastify: "*"
  "@fastify/helmet@*":
    peerDependencies:
      fastify: "*"
  "@fastify/passport@*":
    peerDependencies:
      fastify: "*"
  "@fastify/rate-limit@*":
    peerDependencies:
      fastify: "*"
  "@fastify/request-context@*":
    peerDependencies:
      fastify: "*"
  "@fastify/secure-session@*":
    peerDependencies:
      fastify: "*"
  "@fastify/sensible@*":
    peerDependencies:
      fastify: "*"
  "@fastify/static@*":
    peerDependencies:
      fastify: "*"
  "@fastify/view@*":
    peerDependencies:
      fastify: "*"
  "@fastify/websocket@*":
    peerDependencies:
      "@types/ws": "*"
      fastify: "*"
  fastify-graceful-shutdown@*:
    peerDependencies:
      fastify: "*"
  fastify-healthcheck@*:
    peerDependencies:
      fastify: "*"
  oauth2orize-openid@*:
    dependencies:
      oauth2orize: "*"
  oauth2orize-pkce@*:
    peerDependencies:
      oauth2orize: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@ojkelly/plugin-build.cjs
    spec: "https://yarn.build/latest/build"

yarnPath: .yarn/releases/yarn-3.6.1.cjs
