packageExtensions:
  express@*:
    peerDependencies:
      ejs: "*"
    peerDependenciesMeta:
      ejs:
        optional: true
  oauth2orize-openid@*:
    dependencies:
      oauth2orize: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-2.4.1.cjs
