packageExtensions:
  "@oada/well-known-json@*":
    peerDependencies:
      "@types/express": "*"
  express@*:
    peerDependencies:
      ejs: "*"
    peerDependenciesMeta:
      ejs:
        optional: true
  fastify-accepts@*:
    dependencies:
      "@types/accepts": "*"
    peerDependencies:
      fastify: "*"
  fastify-bearer-auth@*:
    peerDependencies:
      fastify: "*"
  fastify-cors@*:
    peerDependencies:
      fastify: "*"
  fastify-graceful-shutdown@*:
    peerDependencies:
      fastify: "*"
  fastify-healthcheck@*:
    peerDependencies:
      fastify: "*"
  fastify-helmet@*:
    peerDependencies:
      fastify: "*"
  fastify-sensible@*:
    peerDependencies:
      fastify: "*"
  fastify-websocket@*:
    peerDependencies:
      "@types/ws": "*"
      fastify: "*"
  oauth2orize-openid@*:
    dependencies:
      oauth2orize: "*"
  under-pressure@*:
    peerDependencies:
      fastify: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@ojkelly/plugin-build.cjs
    spec: "https://yarn.build/latest/build"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
