checksumBehavior: reset

compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@fastify/accepts@*":
    peerDependencies:
      fastify: "*"
  "@fastify/auth@*":
    peerDependencies:
      fastify: "*"
  "@fastify/bearer-auth@*":
    peerDependencies:
      fastify: "*"
  "@fastify/cors@*":
    peerDependencies:
      fastify: "*"
  "@fastify/formbody@*":
    peerDependencies:
      fastify: "*"
  "@fastify/helmet@*":
    peerDependencies:
      fastify: "*"
  "@fastify/passport@*":
    peerDependencies:
      fastify: "*"
  "@fastify/rate-limit@*":
    peerDependencies:
      fastify: "*"
  "@fastify/request-context@*":
    peerDependencies:
      fastify: "*"
  "@fastify/secure-session@*":
    peerDependencies:
      fastify: "*"
  "@fastify/sensible@*":
    peerDependencies:
      fastify: "*"
  "@fastify/static@*":
    peerDependencies:
      fastify: "*"
  "@fastify/view@*":
    peerDependencies:
      fastify: "*"
  "@fastify/websocket@*":
    peerDependencies:
      "@types/ws": "*"
      fastify: "*"
  fastify-graceful-shutdown@*:
    peerDependencies:
      fastify: "*"
  fastify-healthcheck@*:
    peerDependencies:
      fastify: "*"
  oauth2orize-openid@*:
    dependencies:
      oauth2orize: "*"
  oauth2orize-pkce@*:
    peerDependencies:
      oauth2orize: "*"

yarnPath: .yarn/releases/yarn-4.5.0.cjs
